
MAJOR_SCALES = {
        "C major":  ["C", "D", "E", "F", "G", "A", "B", "C"],
        "G major":  ["G", "A", "B", "C", "D", "E", "F#", "G"],
        "D major":  ["D", "E", "F#", "G", "A", "B", "C#", "D"],
        "A major":  ["A", "B", "C#", "D", "E", "F#", "G#", "A"],
        "E major":  ["E", "F#", "G#", "A", "B", "C#", "D#", "E"],
        "B major":  ["B", "C#", "D#", "E", "F#", "G#", "A#", "B"],
        "F# major": ["F#", "G#", "A#", "B", "C#", "D#", "E#", "F#"],
        "C# major": ["C#", "D#", "E#", "F#", "G#", "A#", "B#", "C#"],
        "F major":  ["F", "G", "A", "Bb", "C", "D", "E", "F"],
        "Bb major": ["Bb", "C", "D", "Eb", "F", "G", "A", "Bb"],
        "Eb major": ["Eb", "F", "G", "Ab", "Bb", "C", "D", "Eb"],
        "Ab major": ["Ab", "Bb", "C", "Db", "Eb", "F", "G", "Ab"],
        "Db major": ["Db", "Eb", "F", "Gb", "Ab", "Bb", "C", "Db"],
        "Gb major": ["Gb", "Ab", "Bb", "Cb", "Db", "Eb", "F", "Gb"],
        "Cb major": ["Cb", "Db", "Eb", "Fb", "Gb", "Ab", "Bb", "Cb"],
}

MAJOR_ARPEGGIOS_2OCT = {
    "C major":  ["C", "E", "G", "C", "E", "G", "C"],
    "G major":  ["G", "B", "D", "G", "B", "D", "G"],
    "D major":  ["D", "F#", "A", "D", "F#", "A", "D"],
    "A major":  ["A", "C#", "E", "A", "C#", "E", "A"],
    "E major":  ["E", "G#", "B", "E", "G#", "B", "E"],
    "B major":  ["B", "D#", "F#", "B", "D#", "F#", "B"],
    "F# major": ["F#", "A#", "C#", "F#", "A#", "C#", "F#"],
    "C# major": ["C#", "E#", "G#", "C#", "E#", "G#", "C#"],
    "F major":  ["F", "A", "C", "F", "A", "C", "F"],
    "Bb major": ["Bb", "D", "F", "Bb", "D", "F", "Bb"],
    "Eb major": ["Eb", "G", "Bb", "Eb", "G", "Bb", "Eb"],
    "Ab major": ["Ab", "C", "Eb", "Ab", "C", "Eb", "Ab"],
    "Db major": ["Db", "F", "Ab", "Db", "F", "Ab", "Db"],
    "Gb major": ["Gb", "Bb", "Db", "Gb", "Bb", "Db", "Gb"],
    "Cb major": ["Cb", "Eb", "Gb", "Cb", "Eb", "Gb", "Cb"],
}